# page hotness codes

obj-y += page_info.o
# obj-y += page_hotness.o
obj-y += page_change_prot.o
obj-y += page_hotness_api.o
obj-y += page_gups_test.o
obj-y += candidate_page.o
obj-y += page_exchange.o

obj-y += page_hotness_histogram.o
obj-y += base_histogram.o

obj-y += page_pebs.o
obj-y += page_migrate_prepare.o